### ISSUE TITLE
[SR] Annual Visit-> Health Information skip is not working properly.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#11]
Annual Visit-> Health Information -> Does she remain absent during menstruation? 
Skip is not working properly for this question.

**Comment by vindeolal** [comment]
@garimadosar5 Current skip logic is show `Does she remain absent during menstruation?` when either `School going` is `Yes` or `Menstrual disorders` is other than `No problem`. And this skip logic works fine. Checked in staging. Do we need to change this skip logic?
