### ISSUE TITLE
[SR Report] Report for Exit Reason.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#12]
Ref Doc: https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1750426969

Title of Report - Exit Reason

Metabase Link - https://reporting.openchs.org/question/468

Documentation of Report -  https://github.com/OpenCHS/sewa-rural/wiki#exit-reason

**Comment by vindeolal** [comment]
Report points to staging and can be tested
