### ISSUE TITLE
Linelist Reports are not working

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#137]
Below mentioned linelists giving error : Cannot run the query: missing required parameters: #{"status" "baseline_year" "visit_number"}

1. Line list for Adolescent with Menstrual Disorder
2. Line List for Menstrual Hygeine practices
3. Line List of Chronic Sickness
4. Mild and Normal Anemia Line Listing
5. Moderate Anemia Line listing
6. School Drop out Ration line list
7. Prevalance of Substance Misuse linelist
8. Severe Anemia linelist

**Comment by sachsk** [comment]
These are the linelists for the indicator report so it will not run directly.
