### ISSUE TITLE
[SR Report] Chronic Sickness 

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#14]
##### QA Comments - 
- Chronic sicknesses that are coming form Annual and quarterly visit, are not changing based on quarterly form.  - _Not DONE_
       -  Fever
       - Cough-cold
       - Jaundice
       - Abdominal pain
       - Diarrhoea
       - Other
       - Hospitalization
	

Ref Doc - 
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1750426969

Title of Report - Chronic Sickness

Link of Metabase -  https://reporting.openchs.org/question/472

Link of Report Documentation - https://github.com/OpenCHS/sewa-rural/wiki#chronic-sickness

**Comment by vindeolal** [comment]
`Sickness in last 1 month` question is not asked in quarterly form.
Hospitalization value is taken from latest Annual or Quarterly form from the question `Hospitalized in last 3 months`.

**Comment by vindeolal** [comment]
Included latest of  Annual/Quarterly visit.
