### ISSUE TITLE
[SR Report] Attendance in each fixed Visit

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#15]
Ref Doc - 
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1750426969

Title of Report - Attendance in each fixed Visit

Metabase link - https://reporting.openchs.org/question/473

Documentation Link - https://github.com/OpenCHS/sewa-rural/wiki#attendance-in-each-fixed-visit

**Comment by petmongrels** [comment]
Functionally it is fine.
From the user interface perspective, it would be good to have the order of filter options as:

- All
- various options
- other

Regarding others: since these concepts are displayed like that in the app, this data is available to sort correctly.

**Comment by vindeolal** [comment]
Filter options are automatically getting sorted by Metabase.
