### ISSUE TITLE
[Sewa Rural] Follow-up Visit for Severe Anemic Adolescents

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#150]
Motivation:
Health workers require to do follow up visits of Severe Anemic Adolescents for three months every month and until the status changes to Moderate Anemia.

Goal: 
User is able to complete the follow-up visit of Severe Anemic Adolescents (Hemoglobin<=7)

Form Requirements:
https://docs.google.com/spreadsheets/d/1ToBjRrZJ_KwQi-ngscQBlTjqJo_g_qUGn8ry4E5-kOs/edit#gid=438616642

Encounter Name: Severe Anemia Follow-up
Program: Adolescent
Subject Type: Individual

Acceptance Criteria:
User should be able to successfully complete the follow-up visit of Adolescents suffering with Severe Anemia - with all the necessary details provided in form.

**Comment by AchalaBelokar** [comment]
<img width="387" alt="Screenshot 2022-06-23 at 9 52 43 PM" src="https://user-images.githubusercontent.com/104890488/175348676-27be6f75-a523-4310-ba3b-15efa510e19b.png">
HB after 3 months of treatment  ?must be between 1-20
