### ISSUE TITLE
[Sewa Rural] User should be able to do Follow-up visit for Adolescents with Addiction

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#154]
Motivation:
Health workers require to do follow up visits of Adolescents with Addiction every October-November.

Goal:
User is able to complete the follow-up visit of Adolescents with Addiction. 

Form Requirements:
https://docs.google.com/spreadsheets/d/1ToBjRrZJ_KwQi-ngscQBlTjqJo_g_qUGn8ry4E5-kOs/edit#gid=631582733

Encounter Name: Addiction Follow-up
Program: Adolescent
Subject Type: Individual

Acceptance Criteria:
User should be able to successfully complete the follow-up visit of Adolescents with Addiction - with all the necessary details provided in form.

**Comment by Gojo-Taqi** [comment]
All the forms are created.
Need to write one logic for when to show the addiction follow up encounter in javascript.

**Comment by AchalaBelokar** [comment]
<img width="387" alt="Screenshot 2022-06-24 at 1 51 44 PM" src="https://user-images.githubusercontent.com/104890488/175494947-5dfeb5a7-3073-4ca0-93a2-e1b867060854.png">
Which type of tobacco are you taking having 3rd option is both.but in the app it is showing other
