### ISSUE TITLE
[Sewa Rural] Endline Visit for Adolescents

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#155]
Motivation: Endline visit is required to be conducted by health workers at the end of every academic year unless the student has moved out of school or exit from the program.

Goal:
As soon as enrollment of Individual is done and Annual Visit - Baseline is completed, Annual Visit - Endline should be visible in Planned visits for user to conduct.

Form requirements:
https://docs.google.com/spreadsheets/d/1ToBjRrZJ_KwQi-ngscQBlTjqJo_g_qUGn8ry4E5-kOs/edit#gid=1846320309

Encounter to be created against Adolescent Program.
Name of encounter: Annual Visit - Endline
Subject Type - Individual.

Acceptance Criteria:
The user should be able to conduct the Annual Visit - Endline with all the necessary details and rules provided in the requirement form.

**Comment by AchalaBelokar** [comment]
1) Are you present in school?  If the answer is no then only show the from how many days options
2) Additional  Medical  History Is there any other condition you want to mention about him/her? must be multi-select.
