### ISSUE TITLE
[Sewa Rural] Exit form for Adoelscent program

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#157]
Motivation:
Adolescent can be exit from the Adolescent Program for a number of reasons.

Goal:
User should be able to exit the beneficiary from the Adolescent program by clicking on Enrolment visit details from beneficiary profile. On clicking Exit form should be displayed for Program exit.

Form Requirements:
https://docs.google.com/spreadsheets/d/1ToBjRrZJ_KwQi-ngscQBlTjqJo_g_qUGn8ry4E5-kOs/edit#gid=83566980

Encounter name: Adolescent Exit (this will already be there when program was created)
Subject type: Individual
Program: adolescent

Acceptance Criteria:
User is able to exit the adolescent from program by selecting a proper reason and providing necessary details as mentioned in form.

**Comment by AchalaBelokar** [comment]
<img width="387" alt="Screenshot 2022-06-24 at 4 33 03 PM" src="https://user-images.githubusercontent.com/104890488/175522290-fec5cd36-2a5d-446d-b827-625eaace3cb6.png">
when we select death option then Cause of Death and death related operation will come in the from

**Comment by AchalaBelokar** [comment]
the date is equal less than current date
