### ISSUE TITLE
[Sewa Rural] Uploading Locations

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#158]
Goal:
Locations for following location types to be uploaded for Adolescent organization. All locations are on the same hierarchy level.

1. Village
2. School
3. Boarding

Acceptance criteria:
The locations should be visible in address options for Individual registration once the user selects Village/School or Boarding.

Existing list of locations can be found from app in production.

**Comment by AchalaBelokar** [comment]
<img width="387" alt="Screenshot 2022-06-30 at 11 48 33 AM" src="https://user-images.githubusercontent.com/104890488/176616370-beeae329-72e7-42ba-a2e3-15d544fddec0.png">
I am choosing the master catchment still it is showing the only one location

**Comment by utkarshavni** [comment]
This is already in UAT and showing all locations under Master so moving this to deploy ready.
