### ISSUE TITLE
[SR Report] School Going Children

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#16]
Ref Doc - 
https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1750426969

Title of Report  - School Going Children

Metabase Link -  https://reporting.openchs.org/question/469

Documentation Link - https://github.com/OpenCHS/sewa-rural/wiki#school-going-children

**Comment by vindeolal** [comment]
Report points to Staging and can be tested.
