### ISSUE TITLE
[Sewa Rural] School Drop-out Visit

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#160]
Motivation:
Health workers will visit home of the adolescent in case they are dropped out of school.

Goal:
User is able to conduct a planned visit to home of Adolescent if they are dropped out of school. This visit is done when "Dropped Out" is selected in School Going in either of the annual visit.

Form Requirements:
https://docs.google.com/spreadsheets/d/1ToBjRrZJ_KwQi-ngscQBlTjqJo_g_qUGn8ry4E5-kOs/edit#gid=489917620

Acceptance Criteria:
User should be able to successfully fill School drop-out form for adolescents who have dropped out of school with necessary details provided in form.

**Comment by AchalaBelokar** [comment]
<img width="387" alt="Screenshot 2022-06-24 at 12 42 10 PM" src="https://user-images.githubusercontent.com/104890488/175482837-b6413487-58e1-4413-8bf6-e3399699ae26.png">
The name of the school option appears only as the answer to this question is YES: Are you ready to readmit in school?
