### ISSUE TITLE
[Sewa Rural] Hb values should not show Anaemia status in Program Summary

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#164]
Issue:

In Adolescent Program summary, Hb values should show Hemoglobin values taken at different times during the visits in Program. Currently it is showing Anaemia Status.

Attaching screenshot for reference:
![Program Summary.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/8d4bf581-374b-496a-9f43-1f978929786a)

**Comment by Gojo-Taqi** [comment]
The summary headline/heading for moderate or severe anaemia must be **Anaemic status**.
