### ISSUE TITLE
[SEWA Rural] - Adolescent UAT Feedback Field level changes

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#172]
Changes to be done mentioned in the sheet:
https://docs.google.com/spreadsheets/d/1ToBjRrZJ_KwQi-ngscQBlTjqJo_g_qUGn8ry4E5-kOs/edit#gid=1675076568

Changes which have Status marked as "Active" are to be done.

**Comment by Gojo-Taqi** [comment]
20 - 25 mins for adding the search fields on filter
