### ISSUE TITLE
[Sewa Rural] Service Delivery Reports

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#186]
Service Delivery Reports for new Adolescent organization. Report logic remains same as past reports for Adolescent program.

**Goal:**
Following reports as displayed on metabase currently should be there for new Adolescent program except "Assessment of Helpline reports".
https://reporting.avniproject.org/collection/162-service-delivery-related-reports

Report r4equirements:
https://docs.google.com/spreadsheets/d/1sNBpK0UPP8srmbvyn7SfXPRCurU0RFwv3zZN4In_JK0/edit#gid=0

**Comment by sachsk** [comment]
report directory:- https://reporting.avniproject.org/collection/446-service-delivery-reports

report "Status of Vulnerability follow-up visits" is remaining as data points are not clear
