### ISSUE TITLE
[Sewa Rural] Data migration for duplicate location

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#187]
- [x] Location from where data needs to be migrated - "અમલઝર માધ્યમિક", Id - 129221
      To Location - "Amalzar Secondary", Id - 130975
      Remove "અમલઝર માધ્યમિક", Id - 129221 location after the migration is done.

- [x] Location from where data needs to be migrated - "Dharoli Secondary", Id - 130986
        To Location - "ધારોલી માધ્યમિક", Id - 129240
        Remove "Dharoli Secondary", Id - 130986  location after the migration is done.

- [x] Location from where data needs to be migrated - "રાણીપુરા, કેજીબીવી", Id - 129220
       To Location - "Ranipura Girls KGBV", Id - 130988
        Remove "રાણીપુરા, કેજીબીવી", Id - 129220 location after the migration is done.

**Comment by Gojo-Taqi** [comment]
Estimated time of completion :- 0.5 hrs

**Comment by Gojo-Taqi** [comment]
For id 129221 - Number of individual rows affected = 16
For id 129221 - Number of program_enrolment rows affected = 16
For id 129221 - Number of program_encounter rows affected = 39,

For id 129240 - Number of individual rows affected = 26
For id 129240 - Number of program_enrolment rows affected = 26
For id 129240 - Number of program_encounter rows affected = 56,

For id 129220 - Number of individual rows affected = 11
For id 129220 - Number of program_enrolment rows affected = 10
For id 129220 - Number of program_encounter rows affected = 20,
