### ISSUE TITLE
[Sewa Rural] Misc changes

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#189]
- [x] Remove helpline questions from annual visits.
- [x] Counseling points to be displayed for Sickle Cell trait
- [x] Counseling points to be displayed for Obesity  (in endline and baseline if BMI is greater than 24.9)
https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit#gid=546583763
- [x] Change "Adolescent" Program button color to blue from Red.
- [x] Iron tablets question in Moderate anemia is not accepting single digit value, it should accept.

**Comment by Gojo-Taqi** [comment]
Counselling points done for sickle cell trait, 
waiting for obese

**Comment by AchalaBelokar** [comment]
Counseling points to be displayed for Obesity not showing
