### ISSUE TITLE
[Sewa Rural Support] Report issues and changes

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#191]
**Ticket reference:**
https://avni.freshdesk.com/a/tickets/2208

**Following reports need to be fixed/updated**
- [x] Prevalence of Anemia
- [x] Prevalence of Sickle cell anemia
- [x] Prevalence of Malnutrition
- [x] Service delivery reports. 

**Issues sheet reference:**
https://docs.google.com/spreadsheets/d/1iN1UcScuNKr0tk8F_MIrt8cyDyBGdGGi/edit#gid=1164875087

**Changes made in requirement doc for reports 1 to 3:**
https://docs.google.com/spreadsheets/d/1sNBpK0UPP8srmbvyn7SfXPRCurU0RFwv3zZN4In_JK0/edit#gid=2078905339

**Comment by Gojo-Taqi** [comment]
https://reporting.avniproject.org/question/2339-prevalence-of-anemia-new

**Comment by AchalaBelokar** [comment]
Prevalence Animea 
- [x] The count of Total adolescents enrolled is mismatch with data entry app. I  checked in morning  evening  and night but it is not updated in the metabase.

**Comment by Dinesh2019** [comment]
Prevalence Animea 

The count of Total adolescents enrolled is mismatch with the data. In the metabase the total value = 2665 and database value = 2668

**Comment by Dinesh2019** [comment]
Prevalence Animea

The count of School Total is mismatch with the data. In the metabase the total value = 2055 and database value = 2053
we have the two count mismatch in gender male is metabase we have 1003 and in database we have 1001

**Comment by Dinesh2019** [comment]
we have the count mismatch for HB not recorded in the report we have total count as 12 but in the database we have the count as 10.
Attached the query for references
select *
from program_encounter
where encounter_type_id = 1343
  and encounter_date_time notnull
  and observations ->> '0f283bcc-fa4c-4d98-93fd-cbf1729b770d' is null;

**Comment by sachsk** [comment]
Prevalence of Sickle cell anemia:- 

- voided check is not there.

**Comment by Dinesh2019** [comment]
For Prevalence of Malnutrition we have the count mismatch in metabase for Total adolescents enrolled total count is 2664 but in database is 2663 and for BMI total count is 2659 and is db is 2660

**Comment by sachsk** [comment]
Moving on hold since working on an urgent support ticket.

**Comment by sachsk** [comment]
Queries to test report:https://gist.github.com/sachsk/f4b92f62857f0599de0a90f58d135d9e

**Comment by Dinesh2019** [comment]
Need the help of @sachsk for this card
