### ISSUE TITLE
[Adolescent SR Support] Severe and Moderate Anemia follow-up form and visit changes.

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#201]
Reference ticket:
https://avni.freshdesk.com/a/tickets/2232

- [x] Currently in severe anemia follow-up, a question is asked in every fourth visit "Hb after three months of treatment" - remove this question and the rule that it will be displayed in every fourth visit.
- [x] In follow-up forms of both Moderate and Severe anemia add below questions:
 -  Was hemoglobin tested after last follow-up? Yes/No
 -  "Hemoglobin" - If answer to above question is Yes, this field will be editable and blank, if No selected it should auto populate the latest Hemoglobin value. This hemoglobin concept will be the same as one used  in all other forms so that the hemoglobin is updated after every follow-up visit.  
- [x] Make sure program summary is acordingly updated when Hb value is updated in this form.
- [x] Schedule moderate anemia follow-up quarterly.

Requirement sheet updated for the change, check here for references. 
https://docs.google.com/spreadsheets/d/1ToBjRrZJ_KwQi-ngscQBlTjqJo_g_qUGn8ry4E5-kOs/edit#gid=438616642
https://docs.google.com/spreadsheets/d/1ToBjRrZJ_KwQi-ngscQBlTjqJo_g_qUGn8ry4E5-kOs/edit#gid=982459379

**Comment by AchalaBelokar** [comment]
-![Screenshot 2023-03-08 at 4.20.04 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/ad958cd8-fcbc-4d56-a655-2efbec77728e) 
[ ] Follow up is not generated sever annemia.
pls check the user Ranu Ranu
AchalaB@aduat

**Comment by utkarshavni** [comment]
- [x] Complete first Severe Anemia follow-up. On performing next Severe anemia follow-up, it directly shows Counseling details section. (Beneficiary - Test ticket one)
- [x] Complete first moderate anemia follow-up. On clicking for Second moderate anemia follow-up, app is crashing. (Beneficiary - Test ticket two) Attaching screenshot here![WhatsApp Image 2023-03-10 at 11.20.49.jpeg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/2f0c48cf-7054-4436-8ae8-54b02da19f80)
