### ISSUE TITLE
[SR Support] Some minor changes in app

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/sewa-rural#204]
https://avni.freshdesk.com/a/tickets/2644

- [x] 1. if any addiction required multiple selection 
- [x] 2. staying with home ? -please add in option 1. hostel, and 2. in law  **Did this change in Annual Visit - Baseline Encounter**

- [ ] 3. was heamoglobin tested after last follow up is in english please make it gujrati 
- [ ] 4.BMI mulyo- in this  figure <=14.5 and >25 should become red in color
- [ ] 5 please check filter in all vulnarability when filtered severe malnutrition in master tablet its shows wrong figure.
- [ ] 6. in sickle cell filter is not working in superwiser and master dashboard.
- [ ] 7. su tame shala ma hajar cho? please instead of this write su tame shala ma jav cho ? 
- [ ] 8. if shu tame shala ma hajar cho= jo na toh ketla divas thi ?(at present  jo haa toh ketla divas thi ?)
- [ ] 9. su tame shala ma jai rhya cho ? skip thius question if above no 8 is no 
- [ ] 10. shu tame shala ma hajar cho =ha then dont ask (skip su tame shala ma jai rhya cho )(both sentence meaning is same )
- [ ] 11. sickle cell filter not working 

- [ ] **Make the above changes in UAT** 
- [ ] **Once these are QAed, then move to prod**

**Comment by utkarshavni** [comment]
Closing this card as the ticket has been worked upon as part of a separate story and has been resolved.
