### ISSUE TITLE
[Sewa Rural - Adolescent] Changes in visit scheduling

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#206]
Changes in Visit scheduling for following forms:

- [x] Severe Anemia follow-up form
- [x] Moderate Anemia follow-up form
- [x] Severe Malnutrition follow-up form
- [x] Addiction follow-up
- [x] Chronic Sickness follow-up
- [x] Sickle cell follow-up
- [x] Menstrual absenteeism follow-up
- [x] Annual baseline visit

Reference sheet for logic of scheduling:
https://docs.google.com/spreadsheets/d/1nG5wgo9xeT6b77QYp33OKzOHsox-KYwZ/edit#gid=1664227119

**Comment by arjunk** [comment]
@Gojo-Taqi What is the estimate on this card?

**Comment by arjunk** [comment]
@Gojo-Taqi What is the estimate on this card?

**Comment by Gojo-Taqi** [comment]
ETC :- 2.5 hrs
Time taken :- 3hrs 22 min

**Comment by Dinesh2019** [comment]
After completing the endline visit if we schedule the baseline visit as Hd<7 severa anemia is not scheduled

**Comment by Dinesh2019** [comment]
- [x] Chronic sickness follow-up-After completing the end line visit we will schdeule with baseline again if we complete the baseline again with the sickness as yes first visit is schdeuled but if we complete the visit foe sickness the second visit is not scheduled 
- [x] Menstrual absenteeism follow-up - same as well
- [x] Addiction follow-up - same as well
- [x] Sickle cell follow-up - after completeing the visit in the endline and baseline the sickle question is not displayed

**Comment by Dinesh2019** [comment]
- [x] Severe Malnutrition follow-up - follow up should be done on 1 feb but it is scheduling at 10 nov
- [x] Sickle cell follow-up - follow up should be done on 1 feb but it is scheduling at 10 nov
- [x] Chronic sickness follow-up - After endline only one followup is scheduling
- [x] Menstrual absenteeism follow-up - follow up is scheduling for 4 times 
- [x] Addiction follow-up - follow up is scheduling for 4 times
