### ISSUE TITLE
[Sewa Rural Adolescent] - Misc issues/changes

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#209]
Ticket reference:
https://avni.freshdesk.com/a/tickets/2644 
and 
https://avni.freshdesk.com/a/tickets/2816

- [x] For Staying with Whom question in Baseline and Endline form, add following options in the values.
- Hostel
- In-law
- [x] "If dropped out, in which year he/she has left the school ?" this question should only be visible in Baseline and Endline form if Going to School question's answer is dropped out in the form.
- [ ] The question "Do you have any Addiction" in Baseline and Endline form needs to be multi-select
- [x] Translate "Was hemoglobin tested after last follow-up" to Gujarati.
- [x] If "sickling test done" answer is done for the individual in any of the preivous encounters, then dont show that question and Sickling result status in the Endline or baseline form. 
- [ ] In the Summary, show Hb values in Red if the Hb is below 11.
- [x] Schedule Chronic Sickness follow-up only if any answer apart from No Problem is selected in "Is there any other condition you want to mention about him/her".
- [x] Change range of BMI values to 14.5 to 25.
- [ ] Any value outside the range given above should be displayed in Red in the form as well as in the Program summary. - Applicable for Annual visit-Baseline and Annual Visit - Endline.
- [x] While selecting any of the follow-up visits in the Filters from Filter option in home screen, the "Total" card is not displayed. Enable this from backend.
- [x] Below mentioned individual has been voided by mistake. Unvoid them.
Shreyaben Shaileshbhai Vasava
- [x] Translation issues

**Comment by Gojo-Taqi** [comment]
- I cant show the values of haemoglobin in red if they are less than 11, it's because we are showing all the latest HB values there.
- The BA has to confirm with them about one individual where the option is selected as both for now.

**Comment by Dinesh2019** [comment]
- [ ] "If dropped out, in which year he/she has left the school ?" missing in the endline

**Comment by Dinesh2019** [comment]
For Translation 
- [ ]  In the search filter for section and standard translation is missing
- [ ]  For the location in English for some location Gujarati is displayed 
- [ ]   In Baseline In-laws need to be translate
- [ ]   Severa Anemia Follow up need to be translate
- [ ]   Moderate Anemia Follow up need to be translate
- [ ]   upload database should be translated
