### ISSUE TITLE
[SR Report] Status of Service Delivery

### ISSUE THREAD

**Issue by hithacker** [OpenCHS/sewa-rural#21]
Existing report. Start date and end date filter needs to be added. Some rows to be removed. 
Refer https://docs.google.com/spreadsheets/d/1UlNbspXJTawevvaRAqddWvKK0dYMv7rB9GlJ9Io9D74/edit#gid=1750426969.

Can be tested on Staging https://reporting.openchs.org/question/463

**Comment by vindeolal** [comment]
Comments :
Results shows data from Annual or Quarterly visit whichever is latest.
Changed the query for totalNonExitedEnrolled, earlier it was returning info of individuals that had Annual Visit.
Similarly corrected totalRegistered query.

**Comment by petmongrels** [comment]
There is no date filter.
The indicators are fine.

**Comment by vindeolal** [comment]
Date Filter added
