### ISSUE TITLE
[Adolescent SEWA Rural] Schedule Baseline if Endline is cancelled

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#212]
Ticket:
https://avni.freshdesk.com/a/tickets/2777

**Issue:**
Some of the individuals' Baseline form is not getting scheduled since the "Annual visit-Endline" form is not completed. The users can cancel the Endline visit and that should schedule Baseline form. However, right now no form is getting scheduled if that visit is cancelled.

Organization:
Live app - "Adolescent Sewa Rural"
UAt Org - "Adolescent UAT"

- [x] When  "Annual Visit-Endline" is Cancelled, it should schedule  "Annual Visit-Baseline".  It is not scheduling the subsequent baseline form right now.

**Steps to resolve the ticket:**
- After the above change is done, ask users to Cancel the scheduled Endline visits, it should schedule subsequent Baseline form now.

**Comment by Dinesh2019** [comment]
Test Scenario :

- [x] Endlne cancel need to scheduled baseline visit
- [x] Endline cancel more than two and check the baseline visit as per years 
- [x] Cancel the overdue Endline and verify the baseline is getting scheduled
- [ ] After cancelling the endline with the reason as other and baseline is scheduled got completed and we have to change the reason for endline which is cancelled already to some other reason and if we save it again the baseline visit is getting scheduled.(this need to handle in future)
