### ISSUE TITLE
[Sewa Rural] Change decision logic of Moderate anemia 

### ISSUE THREAD

**Issue by utkarshavni** [OpenCHS/sewa-rural#213]
Organization:
UAT - Adolescent Sewa Rural UAT
Prod - Adolescent Sewa Rural

**Use case**
Based on new requirement, If Hemoglobin recorded is between 8 to 10.9, decision for Moderate Anemia is updated. However, Decisions have to be updated for existing observations.

Tasks:
- [x] Update the logic for decision rule for Moderate anemia - If Hb is greater than 8 and less than 11
1. Annual visit - Baseline encounter
2.  Annual visit - Endline encounter
3.  Severe Anemia followup encounter
4.  Moderate Anemia follow up encounter
- [x] If Hb is greater than 8 and less than 11, schedule Moderate Anemia follow-up. Update the visit scheduling rule in following encounters.
1. Annual visit - Baseline encounter
2.  Annual visit - Endline encounter
3.  Severe Anemia followup encounter
4.  Moderate Anemia follow up encounter
- [x] For all the individuals enrolled in program and has latest Hb value recorded is between 8 to 10.9, the Program summary should update the decision as Moderate Anemia.
- [x] Update the range in dashboard card for "Adolescents having Moderate anemia"
- [x] Decision for "Risk of" and "Anaemic status" is considering value of only less than 8, it should consider less or equal to 8. This will get updated in Baseline.
- [x] Add decision for "Anaemic status" in Severe Anemia follow-up, Moderate Anemia follow-up and Annual visit-Endline form. Condition is same as applied in Annual visit-Baseline form.

**Acceptance criteria**
- If Hb is greater than 8 or less than 11, then individual should be marked with Moderate anemia at the end of form and Moderate Anemia follow-up should be scheduled.

**Comment by utkarshavni** [comment]
@vedfordev 

- [ ] Decision for "Risk of" and "Anaemic status" is considering value of only less than 8, it should consider less or equal to 8. This will get updated in Baseline.
- [ ] Add decision for "Anaemic status" in Severe Anemia follow-up, Moderate Anemia follow-up and Annual visit-Endline form. Condition is same as applied in Annual visit-Baseline form.

**Comment by utkarshavni** [comment]
Created a new card for changes related to migration of existing observations:
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/adolescent-sewa-rural/5

**Comment by utkarshavni** [comment]
@vedfordev  @dinesh2096 
moving this to QA failed due to below mentioned issues.
- [x] On editing enrollment, the Baseline is scheduled again. When editing enrolment, Baseline should not be scheduled again if it exists already.
- [x] Click on Filter from home screen, select one or multiple options in Section and click on Apply. It is giving Fatal error. Sharing the screenshot
![Screenshot_20230731-152425_Avni.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/85fd4de8-9c63-4667-97c4-13a4b81b4f30)

**Comment by vedfordev** [comment]
@utkarshavni  checked with two devices for issue **"Click on Filter from home screen, select one or multiple options in Section and click on Apply. It is giving Fatal error. Sharing the screenshot"** . I am not getting an error. 

for other issue please check once
