### ISSUE TITLE
[SR] Change in Registration form- Block.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#28]
##### QA comment -

- Please add the translation for Specify Other "કૃપા કરી સ્પષ્ટ કરો".

Group "Details" -  Question "Block"
Add an option of "Other" and a new question "Specify Other" (Mandatory).

**Comment by vindeolal** [comment]
Deployed changes in staging.

**Comment by vindeolal** [comment]
Translation added. Staging APK :  https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-d7940-2019-08-13-16-04-23.apk
