### ISSUE TITLE
[SR] Changes in Menstruation related Question.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#31]
https://openchs.freshdesk.com/a/tickets/375

##### QA Comments - 
- For Ist comment in the ticket. "girls staying in the hostel, pl skip staying with whom question."
for this change report "Staging - Status of Parents & Stay" needs to be changed. https://reporting.openchs.org/question/529

**Comment by vinayvenu** [comment]
Changes performed here. 

- Quarterly form spelled "Menstruation" as "Menstrutation" in the form. 
- Several rules mentioned female redundantly. This was removed. 
- Menstruation started will now be shown only if it has never been answered as "Yes"
- The following questions will be shown only if Menstruation Started has ever been Yes. 
  - Absorbent material used
  - Menstrual disorders
  - Are you able to do daily routine work during menstruation?
- "If Yes, Age at Menarche" will be asked only if Menstruation Started is Yes in this visit
- MHM Kit received will be asked for all females
- MHM Kit used will be asked only if Menstruation Started has ever been answered "Yes"
- Quarterly form - "MenstrualDisorderCounselling for SR" will now be shown if there are menstrual disorders. This was earlier being only when "Menstruation started" is "Yes" in this visit

**Comment by vindeolal** [comment]
Staying In Hostel should automatically count boarding students after annual visit.
