### ISSUE TITLE
[SR] Add counselling points in Annual and Quarterly visit for Menstruation and Sickle cell Trait.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#32]
https://openchs.freshdesk.com/a/tickets/374
Don't schedule sickle cell followup form if Sickling Test Result is trait.

##### QA Comment -
- Sickle cell trait counselling - It is showing counselling points of Sickle cell disease.   
https://openchs.freshdesk.com/a/tickets/395
- Do we need to show these sickle cell trait counselling points in the subsequent visit? - Confirm with Pradipta.
- Question "menstruation started" should not ask in subsequent Quarterly or Annual Visit if answered once. _Ignore this, this is added in card #31_

**Comment by vindeolal** [comment]
Deployed in staging.

**Comment by vindeolal** [comment]
@pkundu Do we need to show these sickle cell trait counselling points in the subsequent visit?

**Comment by garimadosar5** [comment]
@vindeolal @vinayvenu We will not show the sickle cell counselling points in subsequent visits. It will be shown only when the child it identified as sickle cell trait.

**Comment by garimadosar5** [comment]
@vinayvenu  I need apk to QA the counselling changes.
