### ISSUE TITLE
[SR] Scheduling on cancellation

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#4]
On cancellation of quarterly schedule next quarterly.
On cancellation of annual schedule next annual.
On cancellation of vulnerability schedule next vulnerability.

Don't generate next visit if exited from program(enrolment).

##### QA Comment  2- 
- On cancel it schedules extra visits.
for eg:
Please check case "Shimla Jahan" on staging.
In this case three visits were scheduled for 10-sep 
1. Chronic 
2. Severe Anemia
3. Addiction.
I cancelled "Addiction Visit".
Now it has 
- Severe Anemia - 10 Sep
- Chronic Sickness - 10 Oct
- Sickle Cell - 10 Oct
- Addiction - 10 Oct
- Severe Malnutrition - 10 Oct
- Moderate Anemia - 10 Oct
- Menstrual Disorder  -10 Oct

##### QA Comments - 
- Cancel option is not there for Vulnerability visits.
- If an Adolescent is exited from the program and then his/her visit got cancelled, it scheduled the next relevant visit.

**Comment by vinayvenu** [comment]
@garimadosar5 Can you please confirm if the annual schedule statement is correct?

**Comment by garimadosar5** [comment]
@vinayvenu 

QA Notes - 
- No Vulnerability is getting scheduled now.
