### ISSUE TITLE
[SR][Support] Vulnerability visit is getting scheduled in past. 

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#52]
https://openchs.freshdesk.com/a/tickets/508

- The scenario is described in the ticket.

**Comment by vindeolal** [comment]
@garimadosar5 
As per the current rule implementation we don't have any check for future visits. So if any past venerability is done then it will get scheduled  to a month after the last venerability visit.
What should be done in such cases? should we not schedule any past visit?

**Comment by garimadosar5** [comment]
Issue Solved.
