### ISSUE TITLE
Add Section in form and filter in MyDashboard

### ISSUE THREAD

**Issue by arjunk** [OpenCHS/sewa-rural#53]
https://openchs.freshdesk.com/a/tickets/502

Ref Doc - https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit#gid=1148779645

#### 1. Annual Visit - Qus 18.4 and 18.5
In Qus 18.4 - Add new options as per the spreadsheet.
Qus 18.5 - This is a new question.

#### 2. Add Section as a custom filter on the dashboard and Search page.
Question 18.5 - Add that as a custom filter.

**Comment by vindeolal** [comment]
Deployed in staging.

**Comment by garimadosar5** [comment]
@vindeolal 
Working on staging. We can deploy this on prod.
