### ISSUE TITLE
[SR][Support] Add 'Specify Other' text field in all the questions with other option.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#54]
https://openchs.freshdesk.com/a/tickets/456

Add Question - 'Specify Other' (Text Field) after every question where 'Other' option is there.

- Annual Visit
- Quarterly Visit
- Sickle cell followup
- Severe Anemia followup
- Severe Malnutrition followup
- School Dropout followup

There are questions with the 'OTHER' option in the above encounters. Check for all the questions with OTHER options in these forms.

**Comment by garimadosar5** [comment]
@sachsk 

Deploy this to Prod

**Comment by sachsk** [comment]
@garimadosar5 
Deployed
