### ISSUE TITLE
[SR] Annual Visit Changes.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#59]
ticket - https://openchs.freshdesk.com/a/tickets/473

##### Ref Doc - 
https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit?pli=1#gid=1148779645

- Add Question 18.2
- Add question 25.2
- Add question 45.

Quarterly Visit - 
Translate Question - 25.2

Addiction - Followup - 
- Add question A1.1

Sickle cell followup-
- Change the question - SCD_13

Severe Anemia followup - 
- Add question - SA_16
 
Chronic Sickness followup - 
- Add question cs_10.

**Comment by garimadosar5** [comment]
@sachsk 

Deploy this on Prod.

**Comment by sachsk** [comment]
@garimadosar5 
Deployed
