### ISSUE TITLE
[SR] Program Summary for Individual

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#6]
##### Show the list of vulnerabilities in Program Summary.
https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit#gid=1042913231

**Comment by arjunk** [comment]
@hithacker @garimadosar5 is this card ready to be picked up?

**Comment by vindeolal** [comment]
Updated the ranges and deployed in staging.
