### ISSUE TITLE
[SR] Gujrati Translation for forms.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/sewa-rural#8]
https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit#gid=1148779645

##### QA Comment - 
• Program Summary Translation is not there.
• Exit form -> exit option -> Lost to followup
• Annual form -> Sickle cell in last 1 month (translation missing).
• System recommendation -> "Refer to the hospital immediately for" is not translated.
• Form names are not translated when the next visit is getting scheduled on the last page of the encounter.
• BMI
• Haemoglobin Test is done -> "Not Done" option is not translated. (In Annual) 
• Sickle cell vulnerability -> "In last month have you suffered from any pain or problem". and next ques "What did you do for your problems (options of this question)". and counselling questions. "What is sickle cell disease (options for this question)" and "What are the symptoms in sickle cell disease?"
• Counselling points are not translated (Sickle cell vulnerability).
• Severe malnutrition followup -> "Are you suffering from any other medical problem? (qus and options of this qus)" and "whether reffered to hospital?"
•Severe malnutrition -> "What will happen if you weight is less?" options of this question are not translated.
• In severe malnutrition followup form -> observation table (all the observations are showing in English.)
• Severe and Moderate Anemia followup -> 
question 
"Iron tablets consumed in last week"
"HB after treatment of 3 months"
"Whether taking B12 folic acid tablets?"
"Whether you know your HB?"
"Whether Anemia video shown"
"What are the symptoms of Anemia" - options of this question
"In which food iron contains are more" - options of this question.
• In severe and Moderate Anemia followup form -> observation table (all the observations are showing in English.)
• Encounter "Sickle cell Vulnerability followup" is not translated.
• Addiction followup- 
Questions - Please look at all the questions, most of the questions are not translated.
Counselling checklist for the same.
• In addiction followup form -> observation table (all the observations are showing in English.)

**Comment by hithacker** [comment]
@garimadosar5 Closing this issue as it's already in production and I have fixed most of the translation issues. Just did a new app release in play store which includes these translations.
