### ISSUE TITLE
[SR] Schedule annual visit after every third quarterly visit

### ISSUE THREAD

**Issue by hithacker** [OpenCHS/sewa-rural#9]
##### QA Comments - 
- #rd quarterly is getting scheduled for the previous year. So after that when Annual visit getting scheduled that is also getting scheduled on 01 July 2019.
https://app.zenhub.com/workspaces/openchs-5cf8e458bf08585333fd64ac/issues/openchs/sewa-rural/33

**Comment by arjunk** [comment]
@hithacker we have released SR, so is this done?

**Comment by hithacker** [comment]
No. We reprioritised this given it was not required for SR to go live. We will do it in this release.
